# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Graphics Gems
email: curtisjhu@berkeley.edu
description: >- # this means to ignore newlines until "baseurl:"
    Collection of projects using OpenGL, Graphics research, and physics.
baseurl: ""
url: "gems.funnyscar.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: funnyscarlabs
github_username:  curtisjhu

favicon: favicon.png

permalink: pretty

# Build settings
theme: just-the-docs
plugins:
  - jekyll-seo-tag
  - jekyll-include-cache

# ga_tracking: 
search_enabled: true
search:
    - focus_shortcut_key: 'k'
nav_enabled: true
nav_sort: case_sensitive
heading_anchors: true
aux_links:
  "GitHub":
    - "https://github.com/curtisjhu/gems"
back_to_top: true
last_edit_timestamp: true

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
enable_copy_code_button: true
